#!/usr/bin/env python
import os
import sys
import torch

sys.path.extend(["/IP-Adapter"])
from diffusers import StableDiffusionXLPipeline

# append project directory to path so predict.py can be imported
sys.path.append(".")

from predict import MODEL_CACHE, base_model_path

# Make cache folder
if not os.path.exists("model-cache"):
    os.makedirs("model-cache")

pipe = StableDiffusionXLPipeline.from_pretrained(
    base_model_path,
    torch_dtype=torch.float16,
    add_watermarker=False,
    cache_dir=MODEL_CACHE,
)
